---
image: quay.io/ansible/molecule:3.0.2
services:
  - docker:dind
before_script:
  - docker info
  - python3 --version

stages:
  - molecule

testing:
  stage: molecule
  script:
    - pip3 install ansible molecule docker
    - ansible --version
    - molecule test
  variables:
    DOCKER_HOST: "tcp://docker:2375"
