---
image: quay.io/ansible/molecule:3.0.2
before_script:
  - apk update && apk add --no-cache docker
  - docker info
  - python3 --version

services:
  - docker:dind

stages:
  - molecule

testing:
  stage: molecule
  script:
    - pip3 install ansible docker
    - ansible --version
    - molecule test