---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: centos/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    tmpfs:
      - /run
    override_command: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        centos_base_enable_epel: true
        centos_base_firewalld: true
        centos_base_packages_list:
          - htop
          - mc
        centos_base_update: true
verifier:
  name: ansible
